@startuml
Actor -> DefaultMethodSecurityExpressionHandler: filter
ExpressionBasedPostInvocationAdvice ->ExpressionBasedPostInvocationAdvice: filterCollection 
ExpressionBasedPostInvocationAdvice -> ExpressionUtils: evaluateAsBoolean
return

@enduml